services:
  - type: web
    name: securecrypt
    runtime: python
    plan: free
    branch: main
    envVars:
      - key: SECRET_KEY
        generateValue: true
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT"